Wget Update 1.24.5
AnacondaRecipes/wget-feedstock pull request #8
Opened 2024-08-26 19:19 UTC by Arishamays1

2024-08-26 19:20 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_b1mh5x1chi/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:24: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-08-27 16:35 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_75g0ku1pzd/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:24: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-08-28 07:28 UTC, skupr-anaconda requested changes

2024-08-28 07:28 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  sha256: fa2dc35bab5184ecbc46a9ef83def2aaaa3f4c9f3c97d4bd19dcb07d4da637de
@Arishamays1 Could you please apply a patch to fix CVE-2024-38428? See an additional info:
- https://github.com/anaconda-distribution/cve-curations/pull/550/files
- https://nvd.nist.gov/vuln/detail/CVE-2024-38428
- https://git.savannah.gnu.org/cgit/wget.git/commit/?id=ed0c7c7e0e8f7298352646b2fd6e06a11e242ace
- https://lists.gnu.org/archive/html/bug-wget/2024-06/msg00005.html

2024-08-28 16:00 UTC, skupr-anaconda approved these changes

2024-08-28 19:55 UTC, ViridianMelody approved these changes

2024-08-28 19:55 UTC, ViridianMelody commented on recipe/meta.yaml
> +  # this patch can be removed.
```suggestion
  # Patching for CVE-2024-38428 is required. Once a cleared version is released,
  # this patch can be removed.
```
Best to be a bit more specific to simplify verifying the fix later.

2024-08-29 02:19 UTC, Arishamays1 commented on recipe/meta.yaml
> +  # this patch can be removed.
Thanks Melody! 😄

2024-08-29 02:45 UTC, merged